### ISSUE TITLE
Code Base is Old

### ISSUE THREAD

**Issue by cmaxwe** [cmaxwe/dl-nhltv#2]
@myteron: This code base is kind of old.

I split into two branches on my local repo...

1. Archived Approach: Similar to this approach but I am checking each part after I download and decode it, so that if there are errors they are flagged and the part is downloaded again. Also after all parts are downloaded, I re-download the m3u8 and make sure it hasn't changed.

2. Live Approach: Instead of downloading the game after it switches status to Archive, I actually download the game as it is livestreaming (uses livestreamer python app). This means that it is ready sooner after the game actually ends and it has actually proven to be a bit more reliable.

I will push my changes at some point soon so you can take a look. Didn't think anyone was actually looking at this stuff... :-)

**Comment by myteron** [comment]
I came over @cmaxwe caseyfw/nhldl onto your script and find it very good. 
It allows to get 60fps and you have the login sorted. Even the branches as they are would be great.

**Comment by myteron** [comment]
Hi @cmaxwe if you could just pump up the branches without merging to master would be great!

**Comment by myteron** [comment]
Hi @cmaxwe got a few changes there in the pipe. Cli command line arguments and some classes unit tests etc. Had to move a few things around please let me what you think

**Comment by cmaxwe** [comment]
Hey @myteron ...uploaded a new project https://github.com/cmaxwe/nhl-dl2

It uses livestreamer and I found it to be more reliable than the version in this repo.

Doesn't have the bells and whistles that you have added (easy install, command line arguments, team lookup, etc.) but for me it works pretty well.

**Comment by myteron** [comment]
Hi @cmaxwe thanks for uploading this. I had a few issues stripping silence with ffmpeg lately creating right size files but without content.  Eager to see how nhl-dl2 is doing. 
Team lookup is pretty modular you should be able to just include and used it. 

`from nhltv_lib.teams import Teams`
`self.nhlTeams.getTeam("Detroit").id`

**Comment by cmaxwe** [comment]
The stripping silence problem was in ffmpeg and it was really odd. Just added something to the ffmpeg command to set the buffer length manually and it seemed to fix it.

I think it is probably a bug where ffmpeg was trying to determine the buffer based on the file it was decoding and for some reason that wasn't happening correctly. Anyway...fixed in my new codebase.

Probably won't add the Team lookup. Honestly I am pretty flat out with other stuff and this works for me so I haven't got a lot of time to make it more user friendly.
